### ISSUE TITLE
Añadir fichero para uso de Task

### ISSUE THREAD

**Issue by LuisArostegui** [LuisArostegui/MyWallet#14]
Como programador, necesito añadir un fichero que me permita ejecutar la herramienta Task seleccionada como herramienta para automatizar tareas para este proyecto, en concreto ese fichero de se debe de llamar Taskfile.yml.

Avanzará en #2, #3, #4, #7.

**Comment by JJ** [comment]
Por favor, tratad de entender qué es un issue. Pista: no es una tarea. Ya lo he indicado muchas veces, incluso dedicado una clase completa a ello.

**Comment by LuisArostegui** [comment]
> Por favor, tratad de entender qué es un issue. Pista: no es una tarea. Ya lo he indicado muchas veces, incluso dedicado una clase completa a ello.

OK, los issues deben de llamar la atención sobre algún problema. Por tanto el "añadir fichero para usar Task" no va a ser nunca un problema, es lo que debo de hacer para cumplir #13. ¿Correcto?
