### ISSUE TITLE
Añadir fichero para gestor de dependecias

### ISSUE THREAD

**Issue by LuisArostegui** [LuisArostegui/MyWallet#16]
Como programador, necesito un fichero go.mod que me ayude a gestionar las dependencias del proyecto.

Avanzará en #2, #3, #4, #7.

**Comment by JJ** [comment]
Si un commit cierra tres issues, es que deberían ser un solo issue. Por otro lado, enlazar HUs arbitrarias sin entender por qué tampoco es una buena práctica.
